staging-settings:
  rpcs:
    - chain-name: base-testnet-sepolia
      url: https://sepolia.base.org  # Public Base Sepolia RPC
      
production-settings:
  rpcs:
    - chain-name: base-mainnet
      url: https://mainnet.base.org  # Public Base Mainnet RPC
      # For production, use a dedicated RPC provider:
      # - Alchemy: https://base-mainnet.g.alchemy.com/v2/YOUR-API-KEY
      # - Infura: https://base-mainnet.infura.io/v3/YOUR-API-KEY
      # - QuickNode: https://your-endpoint.base.quiknode.pro/YOUR-API-KEY
