staging-settings:
  user-workflow:
    workflow-name: microcrop-damage-assessment-staging
    workflow-path: ./damage-assessment-workflow
    config-path: ./damage-assessment-workflow/config.staging.json
    secrets-path: ./secrets.yaml
    
production-settings:
  user-workflow:
    workflow-name: microcrop-damage-assessment-production
    workflow-path: ./damage-assessment-workflow
    config-path: ./damage-assessment-workflow/config.production.json
    secrets-path: ./secrets.yaml
    # Uncomment and set this when deploying from a multi-sig wallet:
    # workflow-owner-address: "0xYourMultiSigAddress"
